version: '2.1'
setup: true
orbs:
  terraform: circleci/terraform@3.1.0
  path-filtering: circleci/path-filtering@0.1.3
workflows:
  generate-config:
    jobs:
       - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            terraform/.* continue-terraform true
